blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/Reqvire/reqvire/tree/main/doc
    about: Check out the documentation and user guide
  - name: 💬 Discussions
    url: https://github.com/Reqvire/reqvire/discussions
    about: Join community discussions, share examples, and get help from other users
  - name: 🔒 Security Issues
    url: https://github.com/Reqvire/reqvire/security/advisories
    about: Report security vulnerabilities privately