name: 🚀 Feature Request
description: Suggest a new feature or enhancement for Reqvire
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? What use case are you trying to address?
      placeholder: |
        I'm always frustrated when...
        As a [user type], I need to...
        Currently, there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: I would like Reqvire to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: 💡 Example Usage
      description: If applicable, show how this feature would work
      render: markdown
      placeholder: |
        ```bash
        reqvire new-command --option value
        ```

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context
      description: Add any other context, screenshots, or references about the feature request.
      placeholder: Links to similar tools, research papers, standards, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: 📋 Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true