name: Auto Tag Release

on:
  push:
    branches:
      - release

permissions:
  contents: write  # needed to create and push tags

jobs:
  auto-tag:
    name: Auto Tag Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: release  # Checkout the release branch
          fetch-depth: 0  # Fetch full history for tagging
          
      - name: Extract version from Cargo.toml
        id: version
        run: |
          VERSION=$(grep -m1 '^version' Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
          
      - name: Check if tag already exists
        id: tag_check
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag $TAG already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag $TAG does not exist"
          fi
          
      - name: Create and push tag
        if: steps.tag_check.outputs.exists == 'false'
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          COMMIT_SHA="${{ github.sha }}"
          
          echo "Creating tag $TAG for release branch commit ${COMMIT_SHA:0:7}"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -a "$TAG" -m "Release version $TAG (auto-tagged from release branch)"
          git push origin "$TAG"
          
          echo "✅ Tag $TAG created and pushed successfully"
          
      - name: Tag already exists
        if: steps.tag_check.outputs.exists == 'true'
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          echo "⚠️  Tag $TAG already exists, skipping tag creation"
          echo "The existing release will not be affected"
          
      - name: Summary
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          COMMIT_SHA="${{ github.sha }}"
          
          echo "## Auto Tag Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${COMMIT_SHA:0:7}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: $TAG" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ steps.tag_check.outputs.exists }}" == "false" ]]; then
            echo "- **Status**: ✅ Tag created and pushed" >> $GITHUB_STEP_SUMMARY
            echo "- **Next**: Release workflow will be triggered automatically" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Status**: ⚠️ Tag already exists (skipped)" >> $GITHUB_STEP_SUMMARY
          fi