name: Rust Tests on PR

on:
  pull_request:
    branches:
      - main  # Change this to match your default branch

jobs:
  test:
    name: Run Rust Tests
    runs-on: ubuntu-latest  # Runs on an Ubuntu machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --verbose

